export const NeutralAvatarOptions = {
  topType: [],
  accessoriesType: [
    'Blank',
    // 'Kurt',
    'Prescription01',
    'Prescription02',
    'Round',
    'Sunglasses',
    'Wayfarers',
  ],
  hatColor: ['White'],
  hairColor: [
    'Auburn',
    'Black',
    'Blonde',
    'BlondeGolden',
    'Brown',
    'BrownDark',
    'Platinum',
    'Red',
    'SilverGray',
  ],
  facialHairType: ['Blank'],
  facialHairColor: [
    'Auburn',
    'Black',
    'Blonde',
    'BlondeGolden',
    'Brown',
    'BrownDark',
    'Platinum',
    'Red',
  ],
  clotheType: [
    'BlazerShirt',
    'BlazerSweater',
    'CollarSweater',
    'GraphicShirt',
    'Hoodie',
    'Overall',
    'ShirtCrewNeck',
    'ShirtScoopNeck',
    'ShirtVNeck',
  ],
  clotheColor: [
    'Black',
    // 'PastelGreen',
    // 'PastelYellow',
    'White',
  ],
  graphicType: [
    'Bat',
    'Cumbia',
    'Deer',
    'Diamond',
    'Hola',
    'Pizza',
    'Resist',
    'Selena',
    'Bear',
    'SkullOutline',
    'Skull',
  ],
  eyeType: [
    // 'Close',
    // 'Cry',
    'Default',
    // 'Dizzy',
    // 'EyeRoll',
    'Happy',
    // 'Hearts',
    // 'Side',
    // 'Squint',
    'Surprised',
    // 'WinkWacky',
  ],
  eyebrowType: [
    'Angry',
    'AngryNatural',
    'Default',
    'DefaultNatural',
    'FlatNatural',
    'RaisedExcited',
    'RaisedExcitedNatural',
    'SadConcerned',
    'SadConcernedNatural',
    'UnibrowNatural',
    'UpDown',
    'UpDownNatural',
  ],
  mouthType: [
    // 'Concerned',
    // 'Disbelief',
    // 'Eating',
    // 'Grimace',
    // 'Sad',
    // 'ScreamOpen',
    // 'Serious',
    'Smile',
    // 'Tongue',
    'Twinkle',
    // 'Vomit',
  ],
  skinColor: [
    // 'Tanned',
    'Yellow',
    'Pale',
    // 'Light',
    'Brown',
    // 'DarkBrown',
    'Black',
  ],
};

export const MaleAvatarOptions = {
  topType: [
    ...NeutralAvatarOptions.topType,
    'NoHair',
    // 'Eyepatch',
    'Hat',
    // 'Turban',
    // 'WinterHat1',
    // 'WinterHat2',
    // 'WinterHat3',
    // 'WinterHat4',
    'ShortHairDreads01',
    'ShortHairFrizzle',
    'ShortHairShaggyMullet',
    'ShortHairShortCurly',
    'ShortHairShortFlat',
    'ShortHairShortRound',
    'ShortHairShortWaved',
    'ShortHairSides',
    'ShortHairTheCaesar',
    'ShortHairTheCaesarSidePart',
  ],
  accessoriesType: [...NeutralAvatarOptions.accessoriesType],
  hatColor: [
    ...NeutralAvatarOptions.hatColor,
    'Black',
    'Blue01',
    'Blue02',
    'Blue03',
    'Gray01',
    'Gray02',
    'PastelBlue',
    'PastelGreen',
    'Red',
  ],
  hairColor: [...NeutralAvatarOptions.hairColor],
  facialHairType: [
    ...NeutralAvatarOptions.facialHairType,
    'BeardMedium',
    'BeardLight',
    'BeardMajestic',
    'MoustacheFancy',
    'MoustacheMagnum',
  ],
  facialHairColor: [...NeutralAvatarOptions.facialHairColor],
  clotheType: [...NeutralAvatarOptions.clotheType],
  clotheColor: [
    ...NeutralAvatarOptions.clotheColor,

    'Blue01',
    'Blue02',
    'Blue03',
    'Gray01',
    'Gray02',
    'PastelBlue',
  ],
  graphicType: [...NeutralAvatarOptions.graphicType],
  eyeType: [...NeutralAvatarOptions.eyeType],
  eyebrowType: [...NeutralAvatarOptions.eyebrowType],
  mouthType: [...NeutralAvatarOptions.mouthType],
  skinColor: [...NeutralAvatarOptions.skinColor],
};

export const FemaleAvatarOptions = {
  topType: [
    ...NeutralAvatarOptions.topType,
    'Hijab',
    'LongHairBigHair',
    'LongHairBob',
    'LongHairBun',
    'LongHairCurly',
    'LongHairCurvy',
    'LongHairDreads',
    'LongHairFrida',
    'LongHairFro',
    'LongHairFroBand',
    'LongHairNotTooLong',
    'LongHairShavedSides',
    'LongHairMiaWallace',
    'LongHairStraight',
    'LongHairStraight2',
    'LongHairStraightStrand',
    'ShortHairDreads02',
  ],
  accessoriesType: [...NeutralAvatarOptions.accessoriesType],
  hatColor: [
    ...NeutralAvatarOptions.hatColor,
    'Heather',
    'PastelOrange',
    'PastelRed',
    'PastelYellow',
    'Pink',
  ],
  hairColor: [...NeutralAvatarOptions.hairColor, 'PastelPink'],
  facialHairType: [...NeutralAvatarOptions.facialHairType],
  facialHairColor: [...NeutralAvatarOptions.facialHairColor],
  clotheType: [...NeutralAvatarOptions.clotheType],
  clotheColor: [
    ...NeutralAvatarOptions.clotheColor,
    'Red',
    'Pink',
    'Heather',
    'PastelRed',
    'PastelOrange',
  ],
  graphicType: [...NeutralAvatarOptions.graphicType],
  eyeType: [...NeutralAvatarOptions.eyeType, 'Wink'],
  eyebrowType: [...NeutralAvatarOptions.eyebrowType],
  mouthType: [...NeutralAvatarOptions.mouthType, 'Default'],
  skinColor: [...NeutralAvatarOptions.skinColor],
};
